import { ChecklistItem, EquipmentType } from '@/types'

type TemplateItem = Omit<ChecklistItem, 'status' | 'observacao' | 'fotos'>

export const EQUIPMENT_LABELS: Record<EquipmentType, string> = {
  pemt: 'PEMT - Plataforma Elevatória Móvel de Trabalho',
  empilhadeira: 'Empilhadeira',
  caminhao_carroceria: 'Caminhão Carroceria',
  guindauto: 'Guindauto / Guindaste',
  manipuladora: 'Manipuladora Telescópica',
  outros: 'Outros Equipamentos',
}

export const EQUIPMENT_ICONS: Record<EquipmentType, string> = {
  pemt: '🏗️',
  empilhadeira: '🚜',
  caminhao_carroceria: '🚛',
  guindauto: '🏗️',
  manipuladora: '🦾',
  outros: '⚙️',
}

// ─── PEMT ─────────────────────────────────────────────────────────────────────
export const PEMT_ITEMS: TemplateItem[] = [
  // Condições Gerais
  { id: 'pemt-1', numero: 1, descricao: 'O alarme/sistema sonoro automático de movimentação/subida e descida está funcionando', categoria: 'Condições Gerais' },
  { id: 'pemt-2', numero: 2, descricao: 'Ponto de ancoragem adequado para atracação do cinto de segurança conforme definido pelo fabricante', categoria: 'Condições Gerais' },
  { id: 'pemt-3', numero: 3, descricao: 'O botão de emergência está funcionando adequadamente', categoria: 'Condições Gerais' },
  { id: 'pemt-4', numero: 4, descricao: 'O dispositivo de emergência que possibilite baixar o trabalhador e a plataforma até o solo em caso de pane elétrica, hidráulica ou mecânica está funcionando adequadamente', categoria: 'Condições Gerais' },
  { id: 'pemt-5', numero: 5, descricao: 'O alarme audível em caso de desacionamento do freio de estacionamento está funcionando', categoria: 'Condições Gerais' },
  { id: 'pemt-6', numero: 6, descricao: 'Dispositivos de segurança que garantam seu perfeito nivelamento no ponto de trabalho, conforme especificação do fabricante', categoria: 'Condições Gerais' },
  { id: 'pemt-7', numero: 7, descricao: 'A alça de apoio interno está em boas condições', categoria: 'Condições Gerais' },
  { id: 'pemt-8', numero: 8, descricao: 'Os dispositivos de comando e sistema de elevação encontram-se operacionais', categoria: 'Condições Gerais' },
  { id: 'pemt-9', numero: 9, descricao: 'Dispositivo de segurança que garantam seu perfeito nivelamento', categoria: 'Condições Gerais' },
  { id: 'pemt-10', numero: 10, descricao: 'Possui indicação da capacidade máxima da carga na cesta', categoria: 'Condições Gerais' },
  { id: 'pemt-11', numero: 11, descricao: 'Horímetro e/ou sistema de identificação da quilometragem estão marcando adequadamente o tempo de funcionamento do equipamento', categoria: 'Condições Gerais' },
  { id: 'pemt-12', numero: 12, descricao: 'Os paineis, cabos, plugs, tomadas e chicotes elétricos são isolados e identificados quanto à tensão', categoria: 'Condições Gerais' },
  { id: 'pemt-13', numero: 13, descricao: 'Possui sistema de proteção contra quedas que atenda às especificações do fabricante ou, na falta dessas, ao disposto da NR-12', categoria: 'Condições Gerais' },
  { id: 'pemt-14', numero: 14, descricao: 'Possui tranca ou fechamento adequado do portão de abertura da cesta', categoria: 'Condições Gerais' },
  { id: 'pemt-15', numero: 15, descricao: 'Os pneus e rodas estão em boas condições (isentos de rachaduras, bolhas, áreas degradadas, avarias, cortes, parafusos soltos, dentre outros)', categoria: 'Condições Gerais' },
  { id: 'pemt-16', numero: 16, descricao: 'O equipamento possui proteção contra choque elétrico', categoria: 'Condições Gerais' },
  { id: 'pemt-17', numero: 17, descricao: 'Fita reflexiva, logotipo da empresa e/ou número de identificação visível à distância', categoria: 'Condições Gerais' },
  { id: 'pemt-18', numero: 18, descricao: 'O equipamento está em boas condições gerais (Isento de oxidação estrutural, corrosão, sem rachaduras de solda, vazamentos, possui identificação do painel de comando etc.)', categoria: 'Condições Gerais' },
  { id: 'pemt-19', numero: 19, descricao: 'O equipamento possui chave geral e/ou dispositivo de manobra (bloqueio) que impeça o acionamento involuntário do equipamento durante a manutenção e/ou intervenção', categoria: 'Condições Gerais' },
  { id: 'pemt-20', numero: 20, descricao: 'Possui extintor de incêndio operacional', categoria: 'Condições Gerais' },
  { id: 'pemt-21', numero: 21, descricao: 'Possui indicação de alcance máximo do braço', categoria: 'Condições Gerais' },
  { id: 'pemt-22', numero: 22, descricao: 'As sinalizações de segurança claras e visíveis, em Português Brasil e em local de fácil acesso e compreensão', categoria: 'Condições Gerais' },
  // Documentação
  { id: 'pemt-d1', numero: 1, descricao: 'Garantia atestada do equipamento', categoria: 'Documentação' },
  { id: 'pemt-d2', numero: 2, descricao: 'Plano de Manutenção preventiva da máquina ou equipamento conforme estabelecido pelo fabricante', categoria: 'Documentação' },
  { id: 'pemt-d3', numero: 3, descricao: 'Registro das últimas manutenções efetuadas por pessoa com capacitação específica para a marca e modelo do equipamento, conforme requisitos do fabricante', categoria: 'Documentação' },
  { id: 'pemt-d4', numero: 4, descricao: 'Manual de operação em língua portuguesa Brasil', categoria: 'Documentação' },
]

// ─── EMPILHADEIRA ──────────────────────────────────────────────────────────────
export const EMPILHADEIRA_ITEMS: TemplateItem[] = [
  // Condições Gerais
  { id: 'emp-1', numero: 1, descricao: 'Bancos (fixos em boas condições) com encosto de cabeça', categoria: 'Condições Gerais' },
  { id: 'emp-2', numero: 2, descricao: 'Buzina ou outro dispositivo sonoro de alerta', categoria: 'Condições Gerais' },
  { id: 'emp-3', numero: 3, descricao: 'Cinto de Segurança para todos os ocupantes', categoria: 'Condições Gerais' },
  { id: 'emp-4', numero: 4, descricao: 'Condições dos garfos (rachaduras, trincas)', categoria: 'Condições Gerais' },
  { id: 'emp-5', numero: 5, descricao: 'Condições dos pneus (TWI - Tyre Work Indication) para PTA pneus "fon filled" (sem câmara de ar)', categoria: 'Condições Gerais' },
  { id: 'emp-6', numero: 6, descricao: 'Condições gerais do equipamento (verificar estado do equipamento e condições inseguras de funcionamento) Pinos e Travas', categoria: 'Condições Gerais' },
  { id: 'emp-7', numero: 7, descricao: 'Espelhos retrovisores', categoria: 'Condições Gerais' },
  { id: 'emp-8', numero: 8, descricao: 'Giroflex', categoria: 'Condições Gerais' },
  { id: 'emp-9', numero: 9, descricao: 'Extintor de incêndio', categoria: 'Condições Gerais' },
  { id: 'emp-10', numero: 10, descricao: 'Faróis e faroletes traseiros e dianteiros', categoria: 'Condições Gerais' },
  { id: 'emp-11', numero: 11, descricao: 'Freio de estacionamento', categoria: 'Condições Gerais' },
  { id: 'emp-12', numero: 12, descricao: 'Acesso protegido onde houver risco de queda superior a 1.8 metros e rota de emergência alternativa quando aplicável', categoria: 'Condições Gerais' },
  { id: 'emp-13', numero: 13, descricao: 'Adesivo de altura máxima permitida na cabine caso o veículo possa bater em estruturas e linhas aéreas', categoria: 'Condições Gerais' },
  { id: 'emp-14', numero: 14, descricao: 'Alarme de ré', categoria: 'Condições Gerais' },
  { id: 'emp-15', numero: 15, descricao: 'Ponto de isolamento com cadeado na posição desligado', categoria: 'Condições Gerais' },
  { id: 'emp-16', numero: 16, descricao: 'Cabines protegidas ou adequadas com ar condicionado para proteção de agentes prejudiciais (ruído e poeira)', categoria: 'Condições Gerais' },
  { id: 'emp-17', numero: 17, descricao: 'Correntes de segurança em reboques (exceto para carretas trailers)', categoria: 'Condições Gerais' },
  { id: 'emp-18', numero: 18, descricao: 'Dispositivo audível de alerta de freio de estacionamento', categoria: 'Condições Gerais' },
  { id: 'emp-19', numero: 19, descricao: 'Falling object protection - FOP (aplicado às atividades que tenham risco de queda de material na cabine do equipamento)', categoria: 'Condições Gerais' },
  { id: 'emp-20', numero: 20, descricao: 'Fitas refletivas em seus lados externos', categoria: 'Condições Gerais' },
  { id: 'emp-21', numero: 21, descricao: 'Logotipo da empresa', categoria: 'Condições Gerais' },
  { id: 'emp-22', numero: 22, descricao: 'Pelo menos dois calços de rodas', categoria: 'Condições Gerais' },
  { id: 'emp-23', numero: 23, descricao: 'Piso anti-derrapante', categoria: 'Condições Gerais' },
  { id: 'emp-24', numero: 24, descricao: 'Motor de arranque / bateria', categoria: 'Condições Gerais' },
  { id: 'emp-25', numero: 25, descricao: 'Vazamento de combustíveis / óleo, Mangueiras / conexões hidráulicas', categoria: 'Condições Gerais' },
  { id: 'emp-26', numero: 26, descricao: 'Limpadores (esguicho água) nos equipamentos com pára-brisa', categoria: 'Condições Gerais' },
  { id: 'emp-27', numero: 27, descricao: 'Luz de freio', categoria: 'Condições Gerais' },
  { id: 'emp-28', numero: 28, descricao: 'Luz de marcha-ré', categoria: 'Condições Gerais' },
  { id: 'emp-29', numero: 29, descricao: 'Tabela de cargas (local visível em Português)', categoria: 'Condições Gerais' },
  { id: 'emp-30', numero: 30, descricao: 'Roll Over Protection - ROP', categoria: 'Condições Gerais' },
  { id: 'emp-31', numero: 31, descricao: 'Partes móveis protegidas, a menos que o risco seja baixo', categoria: 'Condições Gerais' },
  { id: 'emp-32', numero: 32, descricao: 'Volante sem folga na direção', categoria: 'Condições Gerais' },
  { id: 'emp-33', numero: 33, descricao: 'Condição das correntes/torre de elevação/empilhadeiras', categoria: 'Condições Gerais' },
  { id: 'emp-34', numero: 34, descricao: 'Condição estrutural e de regulagem dos garfos de carregamento (sem trincas nem empeno)', categoria: 'Condições Gerais' },
  { id: 'emp-35', numero: 35, descricao: 'Condição estrutural da torre de elevação e grade de encosto', categoria: 'Condições Gerais' },
  { id: 'emp-36', numero: 36, descricao: 'Tempo de resposta da torre de comando/garfos se operam normalmente e sem trancos', categoria: 'Condições Gerais' },
  { id: 'emp-37', numero: 37, descricao: 'Gráfico de carga interno com identificação das capacidades conforme elevação', categoria: 'Condições Gerais' },
  { id: 'emp-38', numero: 38, descricao: 'Rádio de comunicação', categoria: 'Condições Gerais' },
  { id: 'emp-39', numero: 39, descricao: 'Número de identificação visível a uma distância segura', categoria: 'Condições Gerais' },
  // Documentação
  { id: 'emp-d1', numero: 1, descricao: 'Cronograma de Inspeção Periódica e Inspeção diária realizada', categoria: 'Documentação' },
  { id: 'emp-d2', numero: 2, descricao: 'Plano de Manutenção / Registro das Manutenções Preventivas / Registro de Manutenções Corretivas', categoria: 'Documentação' },
  { id: 'emp-d3', numero: 3, descricao: 'Garantia emitida por oficina mecânica ou profissional qualificado, que ateste os sistemas de freio, direção e alinhamento', categoria: 'Documentação' },
  { id: 'emp-d4', numero: 4, descricao: 'Manual de operação em língua portuguesa', categoria: 'Documentação' },
]

// ─── CAMINHÃO CARROCERIA ───────────────────────────────────────────────────────
export const CAMINHAO_ITEMS: TemplateItem[] = [
  { id: 'cam-1', numero: 1, descricao: 'Bancos (fixos em boas condições) com encosto de cabeça', categoria: 'Condições Gerais' },
  { id: 'cam-2', numero: 2, descricao: 'Buzina ou outro dispositivo sonoro de alerta', categoria: 'Condições Gerais' },
  { id: 'cam-3', numero: 3, descricao: 'Cinto de Segurança para todos os ocupantes', categoria: 'Condições Gerais' },
  { id: 'cam-4', numero: 4, descricao: 'Condições dos garfos (rachaduras, trincas)', categoria: 'Condições Gerais' },
  { id: 'cam-5', numero: 5, descricao: 'Condições dos pneus (TWI - Tyre Work Indication) para PTA pneus "fon filled" (sem câmara de ar)', categoria: 'Condições Gerais' },
  { id: 'cam-6', numero: 6, descricao: 'Condições gerais do equipamento (verificar estado do equipamento e condições inseguras de funcionamento) Pinos e Travas', categoria: 'Condições Gerais' },
  { id: 'cam-7', numero: 7, descricao: 'Espátulas de limpeza do rolo (fixas)', categoria: 'Condições Gerais' },
  { id: 'cam-8', numero: 8, descricao: 'Espelhos retrovisores', categoria: 'Condições Gerais' },
  { id: 'cam-9', numero: 9, descricao: 'Esteiras em condições adequadas', categoria: 'Condições Gerais' },
  { id: 'cam-10', numero: 10, descricao: 'Proteção contra projeção de materias em equipamentos de perfuração, sondagem ou rompedores', categoria: 'Condições Gerais' },
  { id: 'cam-11', numero: 11, descricao: 'Faróis e faroletes traseiros e dianteiros', categoria: 'Condições Gerais' },
  { id: 'cam-12', numero: 12, descricao: 'Freio de estacionamento', categoria: 'Condições Gerais' },
  { id: 'cam-13', numero: 13, descricao: 'Acesso protegido onde houver risco de queda superior a dois metros e rota de emergência alternativa. Avaliar pontos de intervenção mecânica, lubrificação e abastecimento', categoria: 'Condições Gerais' },
  { id: 'cam-14', numero: 14, descricao: 'Adesivo de altura máxima permitida na cabine caso o veículo possa bater em estruturas e linhas aéreas', categoria: 'Condições Gerais' },
  { id: 'cam-15', numero: 15, descricao: 'Alarme de ré (exceto para equipamentos bi-direcionais como shutle cars)', categoria: 'Condições Gerais' },
  { id: 'cam-16', numero: 16, descricao: 'Ponto de isolamento com cadeado na posição desligado', categoria: 'Condições Gerais' },
  { id: 'cam-17', numero: 17, descricao: 'Cabines protegidas ou adequadas com ar condicionado para proteção de agentes prejudiciais (ruído e poeira)', categoria: 'Condições Gerais' },
  { id: 'cam-18', numero: 18, descricao: 'Correntes de segurança em reboques (exceto para carretas traillers)', categoria: 'Condições Gerais' },
  { id: 'cam-19', numero: 19, descricao: 'Dispositivo audível de alerta de freio de estacionamento', categoria: 'Condições Gerais' },
  { id: 'cam-20', numero: 20, descricao: 'Falling object protecion - FOP (aplicado às atividades que tenham risco de queda de material na cabine do equipamento)', categoria: 'Condições Gerais' },
  { id: 'cam-21', numero: 21, descricao: 'Logotipo da empresa', categoria: 'Condições Gerais' },
  { id: 'cam-22', numero: 22, descricao: 'Pelo menos dois calços de rodas (para equipamentos que possuem implemento, será dispensado este item)', categoria: 'Condições Gerais' },
  { id: 'cam-23', numero: 23, descricao: 'Piso anti-derrapante', categoria: 'Condições Gerais' },
  { id: 'cam-24', numero: 24, descricao: 'Motor de arranque / bateria', categoria: 'Condições Gerais' },
  { id: 'cam-25', numero: 25, descricao: 'Vazamento de combustíveis / óleo, Mangueiras / conexões hidráulicas', categoria: 'Condições Gerais' },
  { id: 'cam-26', numero: 26, descricao: 'Limpadores (esguicho água) nos equipamentos com pára-brisa', categoria: 'Condições Gerais' },
  { id: 'cam-27', numero: 27, descricao: 'Luz de freio', categoria: 'Condições Gerais' },
  { id: 'cam-28', numero: 28, descricao: 'Luz de marcha-ré', categoria: 'Condições Gerais' },
  { id: 'cam-29', numero: 29, descricao: 'Tabela de cargas (local visível em Português)', categoria: 'Condições Gerais' },
  { id: 'cam-30', numero: 30, descricao: 'Giroflex', categoria: 'Condições Gerais' },
  { id: 'cam-31', numero: 31, descricao: 'Roll Over Protection - ROP', categoria: 'Condições Gerais' },
  { id: 'cam-32', numero: 32, descricao: 'Fitas refletivas em seus lados externos', categoria: 'Condições Gerais' },
  { id: 'cam-33', numero: 33, descricao: 'Número de identificação visível a uma distância segura', categoria: 'Condições Gerais' },
  { id: 'cam-34', numero: 34, descricao: 'Partes móveis protegidas, a menos que o risco seja baixo', categoria: 'Condições Gerais' },
  // Documentação
  { id: 'cam-d1', numero: 1, descricao: 'Cronograma de Inspeção Periódica e Inspeção diária realizada', categoria: 'Documentação' },
  { id: 'cam-d2', numero: 2, descricao: 'Plano de Manutenção / Registro das Manutenções Preventivas / Registro de Manutenções Corretivas', categoria: 'Documentação' },
  { id: 'cam-d3', numero: 3, descricao: 'Garantia emitida por oficina mecânica ou profissional qualificado', categoria: 'Documentação' },
  { id: 'cam-d4', numero: 4, descricao: 'Manual de operação em língua portuguesa', categoria: 'Documentação' },
]

// ─── GUINDAUTO ─────────────────────────────────────────────────────────────────
export const GUINDAUTO_ITEMS: TemplateItem[] = [
  { id: 'gui-1', numero: 1, descricao: 'Ar condicionado ou climatizador na cabine de operação (guindaste) ou cabine do caminhão (guindauto)', categoria: 'Condições Gerais' },
  { id: 'gui-2', numero: 2, descricao: 'Bancos fixos em bom estado de conservação, sem defeitos e com encosto de cabeça', categoria: 'Condições Gerais' },
  { id: 'gui-3', numero: 3, descricao: 'Não possui assentos laterais (fixados de modo que o passageiro fique no sentido perpendicular à direção de deslocamento do equipamento)', categoria: 'Condições Gerais' },
  { id: 'gui-4', numero: 4, descricao: 'Maçaneta das portas (trancas externas e internas)', categoria: 'Condições Gerais' },
  { id: 'gui-5', numero: 5, descricao: 'Parte elétrica de sinalização e sonora (setas, farois, lanternas, luz de freio, buzina, alarme sonoro de marcha a ré) e bateria com proteção nos polos', categoria: 'Condições Gerais' },
  { id: 'gui-6', numero: 6, descricao: 'Cinto de Segurança (Tipo três pontos)', categoria: 'Condições Gerais' },
  { id: 'gui-7', numero: 7, descricao: 'Sistema de Monitoramento do veículo (Tacógrafo) - apenas para equipamentos rodoviários', categoria: 'Condições Gerais' },
  { id: 'gui-8', numero: 8, descricao: 'Extintor de Incêndio (proporcional ao veículo/equipamento)', categoria: 'Condições Gerais' },
  { id: 'gui-9', numero: 9, descricao: 'Sistema de monitoramento de carga: Célula de carga ou LMI - Indicador de momento de carga, com indicação ao operador o nível da operação (Aplicável para guindastes)', categoria: 'Condições Gerais' },
  { id: 'gui-10', numero: 10, descricao: 'Data Logger (Caixa Preta) para registro e armazenamento de dados de operação', categoria: 'Condições Gerais' },
  { id: 'gui-11', numero: 11, descricao: 'Mecanismo de nivelamento (Inclinômetro para medir inclinação em graus) Aplicável para Guindauto e Guindastes', categoria: 'Condições Gerais' },
  { id: 'gui-12', numero: 12, descricao: 'Sistema de proteção (limitador de operação segura) que atue em caso de sobrecarga (elétrico, mecânico ou hidráulico)', categoria: 'Condições Gerais' },
  { id: 'gui-13', numero: 13, descricao: 'Sistema de iluminação externa (ECRL - tipo semáforo), com alarme sonoro, que indica o inclinômetro e se equipamento está operando de forma segura', categoria: 'Condições Gerais' },
  { id: 'gui-14', numero: 14, descricao: 'Espelhos Retrovisores (interno e externo)', categoria: 'Condições Gerais' },
  { id: 'gui-15', numero: 15, descricao: 'Para brisa, Limpador e Esguicho de água em boas condições', categoria: 'Condições Gerais' },
  { id: 'gui-16', numero: 16, descricao: 'Condições dos Pneus (Tread Wear Indicator), e Pneu estepe (Caso não exista equipe de resgate mecânico)', categoria: 'Condições Gerais' },
  { id: 'gui-17', numero: 17, descricao: 'Tabela de carga ou gráfico de carga em local visível/acessível no equipamento para indicação das capacidades de carga conforme configuração', categoria: 'Condições Gerais' },
  { id: 'gui-18', numero: 18, descricao: 'Fitas refletivas em seus lados externos', categoria: 'Condições Gerais' },
  { id: 'gui-19', numero: 19, descricao: 'Aviso para "não pertubar o operador" afixado na cabine', categoria: 'Condições Gerais' },
  { id: 'gui-20', numero: 20, descricao: 'Identificação da capacidade nominal do equipamento e da capacidade do moitão ou gancho (em Kg ou toneladas métricas)', categoria: 'Condições Gerais' },
  { id: 'gui-21', numero: 21, descricao: 'Aviso de altura máxima permitida na cabine caso o veículo possa bater em estruturas e linhas aéreas', categoria: 'Condições Gerais' },
  { id: 'gui-22', numero: 22, descricao: 'Legenda nos comandos ou no console de operação', categoria: 'Condições Gerais' },
  { id: 'gui-23', numero: 23, descricao: 'Logotipo da empresa e número de identificação alfanumérica visível a uma distância segura, nas laterais e traseira', categoria: 'Condições Gerais' },
  { id: 'gui-24', numero: 24, descricao: 'Partida do motor', categoria: 'Condições Gerais' },
  { id: 'gui-25', numero: 25, descricao: 'Anemômetro instalado na ponta da lança (aplicado a Guindastes)', categoria: 'Condições Gerais' },
  { id: 'gui-26', numero: 26, descricao: 'Calços de rodas (mínimo 2) e calços de patolamento (material resistente e no mínimo 3 vezes a área da sapata)', categoria: 'Condições Gerais' },
  { id: 'gui-27', numero: 27, descricao: 'Protetor lateral, e parachoques dianteiros e traseiros', categoria: 'Condições Gerais' },
  { id: 'gui-28', numero: 28, descricao: 'Proteção do eixo cardan e demais partes rotativas', categoria: 'Condições Gerais' },
  { id: 'gui-29', numero: 29, descricao: 'Mangueiras hidráulicas estão em boas condições', categoria: 'Condições Gerais' },
  { id: 'gui-30', numero: 30, descricao: 'Comando do munck dos dois lados (se controle remoto, evidenciar treinamento do operador neste tipo de comando)', categoria: 'Condições Gerais' },
  { id: 'gui-31', numero: 31, descricao: 'Ausência de dispositivo de "queda livre" ou o bloqueio físico deste dispositivo que impeça o uso da função de queda livre da carga', categoria: 'Condições Gerais' },
  { id: 'gui-32', numero: 32, descricao: 'Tempo de resposta de comandos/movimentos (se opera sem trancos) e sistema de acionamento de sapatas funcionando normalmente', categoria: 'Condições Gerais' },
  { id: 'gui-33', numero: 33, descricao: 'Para guindauto: dispositivo que emite um sinal sonoro para alertar sobre o acionamento do freio de estacionamento (freio de mão)', categoria: 'Condições Gerais' },
  { id: 'gui-34', numero: 34, descricao: 'Sistema de travamento da cabine que impeça o basculamento acidental em operação (ou em manutenção)', categoria: 'Condições Gerais' },
  { id: 'gui-35', numero: 35, descricao: 'Chave de fim-de-curso e de alarme que indique seu limite em condições operacionais', categoria: 'Condições Gerais' },
  { id: 'gui-36', numero: 36, descricao: 'Trava de segurança do gancho', categoria: 'Condições Gerais' },
  { id: 'gui-37', numero: 37, descricao: 'Fixação adequada do cabo de aço (cunha/soquete) e fixação do moitão adequada para transporte e deslocamentos', categoria: 'Condições Gerais' },
  { id: 'gui-38', numero: 38, descricao: 'Freio de serviço e freio de estacionamento', categoria: 'Condições Gerais' },
  { id: 'gui-39', numero: 39, descricao: 'Integridade das polias de passadas de cabos de aço', categoria: 'Condições Gerais' },
  { id: 'gui-40', numero: 40, descricao: 'Acessórios de içar (cabos de aço, cintas, olhais e manilhas) em boas condições de uso e em conformidade com as Normas (NBR ISO 2408; NBR 10070; NBR 11.900; NBR 13.541; NBR ISO 13.542)', categoria: 'Condições Gerais' },
  { id: 'gui-41', numero: 41, descricao: 'Roll Over Protection (ROP): Todos os veículos 4 x 4; Munck e equipamentos que acessam Mina e Barragem exceto ônibus e vans', categoria: 'Condições Gerais' },
  { id: 'gui-42', numero: 42, descricao: 'Rádio de comunicação', categoria: 'Condições Gerais' },
  { id: 'gui-43', numero: 43, descricao: 'Estabilizadores de patolamento (patolas) dianteiro e traseiro nos caminhões (Munck)', categoria: 'Condições Gerais' },
  { id: 'gui-44', numero: 44, descricao: 'Cones de sinalização (mínimo 4) e triângulo (mínimo 3)', categoria: 'Condições Gerais' },
  { id: 'gui-45', numero: 45, descricao: 'Escada para acesso ao equipamento (Guindaste) e carroceria (Munck) em boas condições. Carroceria possui pontos adequados para apoio, fixação e amarração de cargas', categoria: 'Condições Gerais' },
  { id: 'gui-46', numero: 46, descricao: 'Trava de segurança para tampa da carroceria', categoria: 'Condições Gerais' },
  { id: 'gui-47', numero: 47, descricao: 'Alerta de By-Pass do Guincho Auxiliar', categoria: 'Condições Gerais' },
  { id: 'gui-48', numero: 48, descricao: 'Sinal sonoro para alerta de acionamento do freio de estacionamento (freio de mão)', categoria: 'Condições Gerais' },
  // Documentação
  { id: 'gui-d1', numero: 1, descricao: 'Cronograma de Inspeção Periódica e Inspeção diária realizada', categoria: 'Documentação' },
  { id: 'gui-d2', numero: 2, descricao: 'Plano de Manutenção / Registro das Manutenções Preventivas / Registro de Manutenções Corretivas (Caminhão e mecanismos de içamento)', categoria: 'Documentação' },
  { id: 'gui-d3', numero: 3, descricao: 'Garantia emitida por oficina mecânica ou profissional qualificado, que ateste os sistemas de freio, direção e alinhamento', categoria: 'Documentação' },
  { id: 'gui-d4', numero: 4, descricao: 'Laudo de Teste Líquido Penetrante e Ultrassom nos ganchos/moitão e Registro de Medição métrica nos ganchos (Semestral)', categoria: 'Documentação' },
  { id: 'gui-d5', numero: 5, descricao: 'Manual de operação do Guindaste e Munck em língua portuguesa', categoria: 'Documentação' },
  { id: 'gui-d6', numero: 6, descricao: 'Possui linha de vida ou guarda corpo para as atividades com risco de queda', categoria: 'Documentação' },
]

// ─── MANIPULADORA ──────────────────────────────────────────────────────────────
export const MANIPULADORA_ITEMS: TemplateItem[] = [
  { id: 'man-1', numero: 1, descricao: 'Possui para-brisas frontais laminados ou temperados com película de segurança ou policarbonato', categoria: 'Condições Gerais' },
  { id: 'man-2', numero: 2, descricao: 'Possui luz intermitente, giratória ou estroboscópica (giroflex)', categoria: 'Condições Gerais' },
  { id: 'man-3', numero: 3, descricao: 'Possui extintor de incêndio com carga plena proporcional ao equipamento e no prazo de validade para recarga', categoria: 'Condições Gerais' },
  { id: 'man-4', numero: 4, descricao: 'As luzes e indicadores do(s) painel(eis) estão funcionando e, após a partida do motor, estão sem indicação de falhas sinalizadas por luzes na cor vermelha', categoria: 'Condições Gerais' },
  { id: 'man-5', numero: 5, descricao: 'As luzes de freio e ré estão operacionais', categoria: 'Condições Gerais' },
  { id: 'man-6', numero: 6, descricao: 'Possui iluminação e alarme sonoro para manobras em marcha a ré', categoria: 'Condições Gerais' },
  { id: 'man-7', numero: 7, descricao: 'Setas dianteiras e laterais, luzes de freio e marcha a ré, piscas alerta e faróis de operação e lanternas traseiras funcionando adequadamente', categoria: 'Condições Gerais' },
  { id: 'man-8', numero: 8, descricao: 'Possui cinto de segurança do tipo dois pontos para o operador', categoria: 'Condições Gerais' },
  { id: 'man-9', numero: 9, descricao: 'Possui assento para o condutor regulável', categoria: 'Condições Gerais' },
  { id: 'man-10', numero: 10, descricao: 'O equipamento está isento de vazamentos (óleo, combustível, gás e/ou água) e avarias', categoria: 'Condições Gerais' },
  { id: 'man-11', numero: 11, descricao: 'Possui dispositivo limitador de velocidade', categoria: 'Condições Gerais' },
  { id: 'man-12', numero: 12, descricao: 'A alavanca seletora de velocidade (frente e ré) está operacional', categoria: 'Condições Gerais' },
  { id: 'man-13', numero: 13, descricao: 'Possui FOPS - Falling Objects Protective Structure para prevenção de risco de queda de material sobre a cabine (Facultativo)', categoria: 'Condições Gerais' },
  { id: 'man-14', numero: 14, descricao: 'Possui ROPS - Roll Over Protective Structure para prevenção de risco de tombamento (Facultativo)', categoria: 'Condições Gerais' },
  { id: 'man-15', numero: 15, descricao: 'A torre de elevação, correntes e/ou protetor de carga estão isentos de trincas e avarias', categoria: 'Condições Gerais' },
  { id: 'man-16', numero: 16, descricao: 'Possui indicação da capacidade máxima da carga', categoria: 'Condições Gerais' },
  { id: 'man-17', numero: 17, descricao: 'Possui gráfico de carga interno com identificação das capacidades conforme elevação', categoria: 'Condições Gerais' },
  { id: 'man-18', numero: 18, descricao: 'Possui maçaneta com trancas nas portas de acesso (Obrigatório para empilhadeiras com cabine)', categoria: 'Condições Gerais' },
  { id: 'man-19', numero: 19, descricao: 'A buzina, volante, embreagem, acelerador, alavancas, manetes e/ou sistemas de comando estão operacionais', categoria: 'Condições Gerais' },
  { id: 'man-20', numero: 20, descricao: 'Possui sistema para detecção de presença do operador', categoria: 'Condições Gerais' },
  { id: 'man-21', numero: 21, descricao: 'Os garfos estão em condições de uso e livres de trincas visíveis', categoria: 'Condições Gerais' },
  { id: 'man-22', numero: 22, descricao: 'Possui limpadores e esguicho de água', categoria: 'Condições Gerais' },
  { id: 'man-23', numero: 23, descricao: 'Possui adesivos refletivos em seus lados externos e identificação com a logo da empresa', categoria: 'Condições Gerais' },
  { id: 'man-24', numero: 24, descricao: 'As mangueiras hidráulicas estão em boas condições, isentas de deformações, rasgos etc.', categoria: 'Condições Gerais' },
  { id: 'man-25', numero: 25, descricao: 'Possui acionamento hidráulico para abertura e fechamento do garfo', categoria: 'Condições Gerais' },
  { id: 'man-26', numero: 26, descricao: 'A bateria está bem fixada, isenta de vazamentos e com polo positivo protegido', categoria: 'Condições Gerais' },
  { id: 'man-27', numero: 27, descricao: 'Possui piso/plataformas para acesso a cabine antiderrapantes', categoria: 'Condições Gerais' },
  { id: 'man-28', numero: 28, descricao: 'Possui chave geral e/ou dispositivo de manobra (bloqueio) que impeça o acionamento involuntário do equipamento durante a manutenção e/ou intervenção', categoria: 'Condições Gerais' },
  { id: 'man-29', numero: 29, descricao: 'Os espelhos retrovisores estão isentos de avarias e danos, apresentando boas condições de visibilidade', categoria: 'Condições Gerais' },
  { id: 'man-30', numero: 30, descricao: 'As rodas e pneus estão isentos de bolhas, deformações e/ou cortes nas laterais e/ou banda de rodagem (áreas degradadas)', categoria: 'Condições Gerais' },
  { id: 'man-31', numero: 31, descricao: 'Possui no mínimo dois calços para as rodas', categoria: 'Condições Gerais' },
  { id: 'man-32', numero: 32, descricao: 'O volante está isento de folga na direção', categoria: 'Condições Gerais' },
  { id: 'man-33', numero: 33, descricao: 'O freio de estacionamento está operacional', categoria: 'Condições Gerais' },
  { id: 'man-34', numero: 34, descricao: 'As partes móveis estão devidamente protegidas', categoria: 'Condições Gerais' },
  // Documentação
  { id: 'man-d1', numero: 1, descricao: 'Plano de Manutenção preventiva da máquina ou equipamento conforme estabelecido pelo fabricante', categoria: 'Documentação' },
  { id: 'man-d2', numero: 2, descricao: 'Registro da última manutenção preventiva e ou corretiva realizadas conforme Plano de manutenção ou cópia da Nota Fiscal em caso de equipamento novo', categoria: 'Documentação' },
  { id: 'man-d3', numero: 3, descricao: 'Manual de operação do Equipamento em língua portuguesa Brasil', categoria: 'Documentação' },
  { id: 'man-d4', numero: 4, descricao: 'Laudo ou Atestado de Manutenção assinado por profissional qualificado ou legalmente habilitado (se for realizado por engenheiro, apresentar a cópia da ART - Anotação de Responsabilidade Técnica)', categoria: 'Documentação' },
]

export const CHECKLIST_DATA: Record<EquipmentType, TemplateItem[]> = {
  pemt: PEMT_ITEMS,
  empilhadeira: EMPILHADEIRA_ITEMS,
  caminhao_carroceria: CAMINHAO_ITEMS,
  guindauto: GUINDAUTO_ITEMS,
  manipuladora: MANIPULADORA_ITEMS,
  outros: [],
}

export function getChecklistTemplate(tipo: EquipmentType): ChecklistItem[] {
  const items = CHECKLIST_DATA[tipo] || []
  return items.map(item => ({
    ...item,
    status: null,
    observacao: '',
    fotos: [],
  }))
}
